### ISSUE TITLE
My Inclination towards becoming Angular GDE

### ISSUE THREAD

**Issue by aakash14goplani** [santoshyadavdev/gde-githubstar-interest-call#12]
### About Me

I am a Full Stack JavaScript Developer with 7 years of rich experience in developing Web Applications using Node and Angular. I am also experience in developing Hybrid Mobile Applications using Ionic. Apart from Web world, I have good exposure to Content Management Systems using Oracle WebCenter Site and Wordpress.

I have been working on Angular since early 2019, that is, nearly around 4 years of extensive experience in managing, upgrading and supporting enterprise level applications. 

---

### My Work around Angular

* *Personal Projects*: I have created couple of projects surrounding Angular and an overview can be found at https://aakashgoplani.in/projects. These project includes multiple aspects of Angular - from an simple application to the more complex one. From integrating to Firebase to creating dummy application using Ionic, I thieve to get as much as exposure I can during my free time around Angular space.
* *Current Project*: Right now I am working on my personal portfolio https://aakashgoplani.in/. Although this might just sound as another site to you, this actually includes various Angular concepts that I have learned so far. This simple looking website has functionality like:
   - Lazy loading of each page
   - i18n - English and Hindi
   - Reactive programming using RxJs i.e. content is returned as an observable and rendered using async pipe. everywhere!
   - Angular Material
   - Integration with ESLint
   - Content that you see on the page for now is coming from static files but will later be exported to Google Firestore
   - Post connecting with Firestore I will add service workers to cache data on client side and make my portfolio offline available
   - Unit test cases - Yes you read it right, parallely I am working on writing test cases and targeting for 90+% code coverage.
* *Work for Community*:  For now nothing. But this will be my next target. I had attended you previous twitter space and your talk on ng-kerelam and on same lines, I'll first try and target the documentation part of my favourite libraries / packages. Lets hope for the best...

---

### Blogging around Angular

* I do blog about my day-to-day experiences mostly around angular at https://blog.aakashgoplani.in/ also on https://dev.to/aakashgoplani
* Apart from Web Dev, I have worked on Content Management System for around 3 years 2016 - 2018. Here is my work https://aakashgoplani.in/OWCS/ (though you might not be interested in this, but just thought to mention what I use to do before getting introduced to Angular)

---

### Professional Work around Angular

* I am working with Accenture since I graduated in 2015. It's been 6.5 years now and I have worked on 6 projects as an offshore Angular consultant to US  insurance and banking giants.
* I have also given multiple KTs on Angular and conducted cross training skills for folks looking to switch career to Angular with Accenture (its sad that I cannot share much internal details owing to my company policy)
* Apart from this I act as an SME (Subject Matter Expertise) in Angular for Accenture and have consulted 4 projects (across Europe and South America) with Angular related solutions (and again, I cannot share much internal details owing to my company policy, sorry!)

---

### Future Inclination

I aspire to be an Angular GDE. I believe path to GDE will pave a new path for me as an independent consultant for both professional and community driven world. Apart from that it will also help me to get (more personal) exposure to people working with and around Angular space. I need your help to mentor and guide me through the path of becoming GDE. Thanks.

**Comment by santoshyadavdev** [comment]
Join tomorrows call.
