### ISSUE TITLE
GDE interest call

### ISSUE THREAD

**Issue by ezzabuzaid** [santoshyadavdev/gde-githubstar-interest-call#13]
Hi Santosh, I'm Ezz Abuzaid.

I am interested in applying for the Angular GDE program.
Currently, I work as an Angular developer, previously I worked with .Net, Node.js, and Flutter as well. I have a passion for building tools, writing, and researching!

## Open Source Projects
<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><a href='https://github.com/ezzabuzaid/tiny-injector'>Tiny Injector</a></td>
      <td>Mix of .NetCore and Angular dependency injection</td>
    </tr>
    <tr>
      <td><a href='https://github.com/ezzabuzaid/fayona'>Fayona</a></td>
      <td>.NetCore like framework using Node.js</td>
    </tr>
    <tr>
      <td><a href='https://github.com/ezzabuzaid/ngx-request-options'>Ngx-Request-Options</a></td>
      <td>Angular package that make passing properties to interceptors possible</td>
    </tr>
    <tr>
      <td><a href='https://github.com/ezzabuzaid/ngx-form-factory'>Ngx-Form-Factory</a></td>
      <td>Angular package to build complex forms without the need to write any markup boilerplate</td>
    </tr>
    <tr>
      <td><a href='https://github.com/ezzabuzaid/document-storage'>Document Storage</a></td>
      <td>JavaScript package that provides a unified interface for browser storages</td>
    </tr>
    <tr>
      <td><a href='https://github.com/ezzabuzaid/form-validators'>Flutter Form Validators</a></td>
      <td>A set of predefined validators that makes field validation straightforward</td>
    </tr>
  </tbody>
</table>

## Technical Articles
* [React Context In Angular](https://dev.to/ezzabuzaid/react-context-in-angular-i4a)
* [Advance Angular Dynamic Component](https://dev.to/this-is-angular/advance-angular-dynamic-component-12e)
* [Using Inline Web Workers To Improve UI Performance](https://dev.to/ezzabuzaid/using-inline-web-workers-to-improve-ui-performance-540n)
* [A Gentel Introduction to Test in Dart](https://github.com/ezzabuzaid/Flutter-Dart-Test-Session/blob/main/test_session.pdf)
* [Angular Request Augmentation](https://dev.to/ezzabuzaid/angular-request-augmentation-2nd3)
* [Angular Caching](https://dev.to/ezzabuzaid/angular-api-caching-2p12)
* [JavaScript Compute like in Dart](https://dev.to/ezzabuzaid/javascript-dart-compute-2k2f)
* [My Gists](https://gist.github.com/ezzabuzaid)

## Where to reach me
- [LinkedIn](https://www.linkedin.com/in/ezzabuzaid/) 
- [Stackoverflow](https://stackoverflow.com/story/ezzabuzaid)
- [Dev.to](https://dev.to/ezzabuzaid)

**Comment by santoshyadavdev** [comment]
Join tomorrows call.
