### ISSUE TITLE
GDE and GiHub Star call

### ISSUE THREAD

**Issue by rodrigokamada** [santoshyadavdev/gde-githubstar-interest-call#14]
Hi Santosh, I'm Rodrigo Kamada (aka Kamada).

I would like to join the GDE program in the Angular or Web Technologies category.

I'm 38 years old, I’m from Brazil and I graduated from Computer Sciences in 2005.

I'm a technology specialist at [ZENVIA](https://www.zenvia.com/) and I work as a software developer, architect and I'm responsible for some open source projects.

I'm experience with Node.js (JavaScript/TypeScript), Java, Angular, Bootstrap, Ionic, MongoDB, MySQL, PostgreSQL, Redis, Kafka, Docker and Kubernetes.

I started working with WEB and PHP since 2005. I have already worked with JSP and JSF and I work with Angular since 2017 .

I developed my own [website](https://rodrigo.kamada.com.br/) using Angular, Node, MongoDB and Redis where I will post events, podcasts, articles, tutorials and tips to share my knowledge and my experience to help people on their technology journey.

I'm creating a series of articles and tutorials about Angular. I'm writing in portuguese on my [blog](https://rodrigo.kamada.com.br/blog) and in english on the [DEV Community](https://dev.to/rodrigokamada), [Medium](https://rodrigokamada.medium.com/), [Hashnode](https://rodrigokamada.hashnode.dev/), [HackerNoon](https://hackernoon.com/u/rodrigokamada) and [Substack](https://rodrigokamada.substack.com/) and publishing the source code on [GitHub](https://github.com/rodrigokamada).

I participate in events such as lives, mentor in hackathons and workshops. I talked about legacy systems in my last live on 11/08: [https://prensa.li/apicon/jantar-com-devs-entenda-tudo-de-integracao-com-sistemas-legados](https://prensa.li/apicon/jantar-com-devs-entenda-tudo-de-integracao-com-sistemas-legados/)

In addition to the social media already mentioned, I have [LinkedIn](https://www.linkedin.com/in/rodrigokamada), [Twitter](https://twitter.com/rodrigokamada), [npm](https://www.npmjs.com/~rodrigokamada), [Facebook](https://www.facebook.com/rodrigokpd) and [Instagram](https://www.instagram.com/rodrigokamada/).

I have been accepted into the Auth0 Ambassador and SuperTokens Ambassador programs in January 2022.

I would like to be nominated for the GDE program.

Thank you so much!

**Comment by santoshyadavdev** [comment]
https://github.com/santoshyadavdev/gde-githubstar-interest-call/pull/22/files#diff-e1def52aeca0e41e0a29aee3d0e78b5ce8ce3d81e402be7b418c4e616314dc36

**Comment by santoshyadavdev** [comment]
We need some talks in your profile and we will meet again in few months.

**Comment by rodrigokamada** [comment]
> We need some talks in your profile and we will meet again in few months.

Thanks Santosh!
