### ISSUE TITLE
GDE program - Rohan Raj

### ISSUE THREAD

**Issue by rohan1907** [santoshyadavdev/gde-githubstar-interest-call#15]
Hello Sir,
You mentioned on twitter to raise an issue for GDE program.
I am currently an Information Science undergraduate and will be graduating in 2022.
I want to be GDE in Machine Learning and TensorFlow and was hoping you could guide me through the process. 
I have started to write blogs on things I learn. Link: https://dev.to/rohan1907
I was also a Developer Student Clubs lead for my campus where I hosted many sessions on Machine Learning. 
Warmly,
Rohan Raj

**Comment by santoshyadavdev** [comment]
call details https://github.com/santoshyadavdev/gde-githubstar-interest-call/pull/22/files#diff-e1def52aeca0e41e0a29aee3d0e78b5ce8ce3d81e402be7b418c4e616314dc36

**Comment by santoshyadavdev** [comment]
As discussed keep working on Machine Learning and give it 1 year.
