### ISSUE TITLE
GDE Program - Interest call - Sij

### ISSUE THREAD

**Issue by cydal** [santoshyadavdev/gde-githubstar-interest-call#18]
Hi Santosh, 

Thank you for your offer of help. I am interested in applying for the GDE for Machine Learning. I am currently an A.I Lead. I have given some talks and have also hosted a number of workshops. I have also written a number of articles, and I am somewhat active in ML communities.

I am hoping for your help to get a better understanding of what to expect during the vetting process. Thanks again for your time.

**Comment by santoshyadavdev** [comment]
https://github.com/santoshyadavdev/gde-githubstar-interest-call/pull/22/files#diff-e1def52aeca0e41e0a29aee3d0e78b5ce8ce3d81e402be7b418c4e616314dc36

**Comment by cydal** [comment]
Blog Writing
https://sijpapi.medium.com/object-detection-with-yolov3-bbdff1f8e543 - July 2021
https://sijpapi.medium.com/implementing-transfer-learning-from-rgb-to-multi-channel-imagery-f87924679166?source=user_profile - Mar 2021
https://sijpapi.medium.com/topic-modeling-of-scientific-literature-on-online-sexual-abuse-materials-csam-749a3e42250b?source=user_profile - Mar 2021
https://sijpapi.medium.com/connecting-google-colab-to-an-amazon-ec2-instance-b61be9f9cf30 Mar 2021
https://sijpapi.medium.com/global-legislative-review-of-child-sexual-abuse-material-csam-online-grooming-for-sexual-307270bee02f Mar 2021
https://sijpapi.medium.com/preprocessing-time-series-data-for-supervised-learning-2e27493f44ae?source=user_profile Nov 2020

Talks 
https://lnkd.in/djkZ_sWR - Dec 2021
https://omdena.com/blog/online-violence-children/ - Nov 2020
https://drive.google.com/drive/folders/1sLYolc7x-dpeLIWwo8l-UGVjLookepY3 July 2021
https://www.youtube.com/watch?v=Ab5Tc-PuPnE&list=PLEmaI9fqubrbxifMjZOdUWAcvUjajM_rE&index=2 July 2021

**Comment by santoshyadavdev** [comment]
Please continue creating content for the next 7-8 months.
