### ISSUE TITLE
GDE Program - Pierre Terrat

### ISSUE THREAD

**Issue by Pterrat** [santoshyadavdev/gde-githubstar-interest-call#19]
Hi Santosh,

Thank you for your help about GDE program.

I would like to know what is the processus to improve my content to apply for Angular GDE program, later? (I would like to create content for french community in priority)

My Youtube Channel : 
https://www.youtube.com/watch?v=9UH9PE2VdeA&list=PLN5HQ7vzG2ZKBdfypyl-3hFKu0jD9Bd3t

Have a nice day :)

**Comment by santoshyadavdev** [comment]
https://github.com/santoshyadavdev/gde-githubstar-interest-call/pull/22/files#diff-e1def52aeca0e41e0a29aee3d0e78b5ce8ce3d81e402be7b418c4e616314dc36

**Comment by santoshyadavdev** [comment]
We can work for the next 6-7 months and apply once you are ready.
