### ISSUE TITLE
Interested to apply for GDE & GITHUB STAR

### ISSUE THREAD

**Issue by carrycooldude** [santoshyadavdev/gde-githubstar-interest-call#2]
I am working on Machine Learning , Open Source and Community.
Now , I am trying to do more for Community and more people

**Comment by santoshyadavdev** [comment]
Join the call mentioned in PR, also please add more details about your work

**Comment by carrycooldude** [comment]
Founder at [OpInCo Community](https://www.youtube.com/c/OpInCoCommunity). I am passionate about Machine Learning and Open Source. I am a GSOC'21 Student in the org of Tensorflow under the tfjs project. Organizer at Developer Days where I am impacted 5k+ people through our program on Web, Mobile, and UI/UX. Speaker at [Open Source Summit Japan](https://www.credly.com/badges/73ae204d-523e-425a-ae87-c1b68a6a94d7?source=linked_in_profile), DevConf US, and many more. I am a GitHub Campus Expert. I am Postman Student Leader. I am also Co-Organizer at TFUG Chandigarh, Kotlin User Group Durg, Mozilla Durg. Organizer at Azure Developer Community Raipur. Mentor at different Communities like DevScript, BashWoman Community, SWOC, and many more. I am also a Google Cloud Ready Facilitator. I am also a Microsoft Learn Student Ambassador and AngelHack Ambassador.
