### ISSUE TITLE
how to figure out when to apply for a GDE

### ISSUE THREAD

**Issue by Chinmay-KB** [santoshyadavdev/gde-githubstar-interest-call#3]
Hi, I'm Chinmay, primarily a Flutter developer for the past 3 years, and like tinkering with other technologies too. 
I occasionally write articles on [dev.to](https://dev.to/chinmaykb), and my latest article is about [route guards in flutter](https://blog.logrocket.com/implementing-route-guards-flutter-web-apps/), and one of my personal fav articles was tweeted about by google dev [just yesterday](https://twitter.com/googledevs/status/1469307204348035081) :D . I've been a part of Google DSC during my college days, and been an Android Study Jam coordinator, [recorded sessions playlist here](https://www.youtube.com/playlist?list=PLxK2vL6QW00f56iGbnBVbXuQ1AxOjH9zw), and have given a few talks while being a part of DSC itself. 

I would like to know what are the things one should have done while applying for being a GDE to maximise their chances?

**Comment by santoshyadavdev** [comment]
Join the call mentioned in PR.
