### ISSUE TITLE
GDE Interest Call

### ISSUE THREAD

**Issue by adityathakurxd** [santoshyadavdev/gde-githubstar-interest-call#4]
Hey Santosh 👋
I wanted to apply for the Google Developer Experts program.

I have been working with [Flutter ](https://flutter.dev/)and have been active in the community with a 700+ member Server of my own. The website for which is: https://teamaditya.co/ We also have mentors onboard to answer any queries that students might have.

### Talks
Previously, I have had the opportunity to talk about building mobile applications at Universities (like VIT Vellore, VIT Chennai, MIT-ADT, Bennet University), and a few other Club events across India.
A Twitter Thread of events I have been a speaker at: https://twitter.com/adityathakurxd/status/1434815333534093313?s=20

I was also a speaker at the Flutter Global Summit and would be in February 2022 speaking at the biggest Nordic Flutter Conference.

### Blog Post
I have written a few and mostly use Medium for all my publications. My Medium profile can be viewed [here](https://adityathakurxd.medium.com/).

- [How to create a chat application in Flutter?](https://adityathakurxd.medium.com/how-to-create-a-chat-application-in-flutter-324bfcca7614)
- [What companies hire Flutter Developers?](https://adityathakurxd.medium.com/what-companies-hire-flutter-developers-74ff52dfe37c)
- [Open Source projects in Flutter](https://adityathakurxd.medium.com/open-source-projects-in-flutter-b6fa96f4d8fc)

### YouTube Channel
I have a 5.05K Subscriber YouTube channel with over a million views where I make videos on tech and profile building. 
**Link**: https://www.youtube.com/channel/UChCAJNpMwoEUYCsE_eSyU4w

### GitHub contribution
I am also a contributor to the Flutter Community Plus Plugins. My contributions can be found [here](https://github.com/fluttercommunity/plus_plugins/pulls?q=is%3Apr+adityathakurxd).

Other than that I also maintain a few Flutter Repositories.

- University: https://github.com/adityathakurxd/university
- SRMOne: https://devlibrary.withgoogle.com/products/firebase/repos/AV-Studios-SRMOne

Would love to know how can I improve my profile and someday become a Google Developer Expert!
Thank you so much! ✨

**Comment by santoshyadavdev** [comment]
Join the call mentioned in PR.
