### ISSUE TITLE
Interested in the GDE program

### ISSUE THREAD

**Issue by DominikPieper** [santoshyadavdev/gde-githubstar-interest-call#6]
Hey 👋,
I’m interested as well about what’s needed to become a GDE and wehstes the best steps to do. 
I used to use Angular a lot but because of changing clients the last year less Angular and more other Web technologies around web.
Mostly around Nx and Nx plugins In my free time.

**Comment by santoshyadavdev** [comment]
Join the call mentioned in PR, also please add more details about your work
