### ISSUE TITLE
Interest to know more about process to be part of GDE and GitHub Stars Program

### ISSUE THREAD

**Issue by DesignrKnight** [santoshyadavdev/gde-githubstar-interest-call#8]
Hi!
I am a passionate open-source and community enthusiast. As a Physics major by University curriculum, I have been actively involved in communities and projects centred on tech due to my immense interest in the field.

I have hands-on experience leading teams building tech projects used at my University by thousands of users across students and professors. I am a full-stack developer in my current job role and have been writing code for production apps. Being a tech enthusiast and a passionate community leader, I am enthusiastic to know more about these programs in detail

**Comment by santoshyadavdev** [comment]
Join the call mentioned in PR, also please add more details about your work

**Comment by DesignrKnight** [comment]
https://g.dev/DesignrKnight

Some details about the work I have done (outside of full-time role)
- Led the Google Developer Student Club at University and was the lead organiser for the first ever full-fledged hackathon of the University

- Led a team of developers and a designer that developed the Institute Counselling Services App, an in-house app for my University, which is the most used app of the institute with over 1.6k monthly active users.

- Mentor and Judge at hackathons almost every week in 2020-21

- Spoken at events on tech and non-tech topic. Some events/topics I have spoken about include
```
1. Tools to help in hackathon for quick development at Silly Hacks, an MLH Member Event
2.  Session on Resume Design, Art of Writing Email at University
3. Jugaad ways to protect APIs at CodeAid, an online fund-raiser for COVID-19
4. Speaker at MLH's annual hacker organiser conference - HACKCON - IX on how to increase visibility of hackathon website
```

- Wrote tech articles. Some of them are
```
1. How To Build a Rate Limiter With Node.js on App Platform at DigitalOcean
2. Setting Up Own Login vs Login via External Services at section.io
3. Why choose MongoDB as your next database? at crio.do

```


What are my plans/goals for the near future (2022)
- Become more proficient in JS
- Learn a new language, maybe Golang
- Get certified in Cloud
- Contribute to open-source projects that are used by large organisations, to get an experience of working in large distributed teams
