### ISSUE TITLE
GDE interest call

### ISSUE THREAD

**Issue by amilamen** [santoshyadavdev/gde-githubstar-interest-call#9]
### Hey there! I'm Amen. 👋
I am interested in applying for the Angular GDE program. I understand that it is a difficult path, but I would just like some guidance for future submission.

### 👨🏻‍💻 About Me
🔭   I’m fullstack JavaScript developer using Angular for front-end and Nest.js (or Express.js) for back-end.

🎓   I 'm Electronics & Embedded Systems Engineer.

📝   I write stuff at [Wetillix Blog (ex Vyconsulting)](https://blog.wetillix.com/).

🌱   Some of my OSS projects are available on my GitHub and Wetillix GitHub.

📫   How to reach me: [LinkedIn](https://www.linkedin.com/in/e-amen-agbla/) and [Twitter](https://twitter.com/ezchilamen)

🎙   I've make some talks at DevFest 2021 for GDG Benin and others panels about PWA in Angular and my package [Ionic Stripe Checkout (library built with Angular)](https://www.npmjs.com/package/@vyconsulting/ionic-stripe-checkout) at Ionic Meetup Zürich.

**Comment by santoshyadavdev** [comment]
Join the call mentioned in PR.
